### ISSUE TITLE
Import in the middle breaks `drizzle-orm` exports

### ISSUE THREAD

**Issue by Lms24** [nodejs/import-in-the-middle#141] opened 2024-07-15 11:06 UTC
## Expected Behavior

Using `import-in-the-middle` works with imports from `drizzle-orm` as with other NPM packages

## Actual Behavior

Registering the `import-in-the-middle` hook causes certain top-level exports from the `drizzle-orm` package to be missing.

This was originally [reported as a bug](https://github.com/getsentry/sentry-javascript/issues/12912) in our Sentry JS SDK repo and I tracked it down to registering the IITM hook as the only thing needed to reproduce the error. 

## Steps to Reproduce the Problem

I created a minimal reproduction example in this repo: https://github.com/Lms24/iitm-bug-drizzle-or

 1. clone repo
 2. `npm install`
 3. run `node index.js`:
     - observe 112 exports from `drizzle-orm` console log
     - script terminates successfully
 4. run `node --import instrument.mjs index.js`
      - observe 85 exports form `drizzle-orm` console log (=> 27 exports missing)
      - script crashes when calling one of the missing functions (e.g. `drizzle.or()`)

## Specifications

  - Version: `import-in-the-middle@1.9.0`
  - Platform: Node 20.11.0
  - Subsystem: MacOS 14.4

**Comment by Lms24** [comment] 2024-07-15 11:12
This is likely a duplicate of https://github.com/nodejs/import-in-the-middle/issues/139.

I'm gonna leave this open until we can confirm that #140 fixes this issue as well. If it does, sorry for the duplicate!

**Comment by timfish** [comment] 2024-07-15 22:19
This is probably not a duplicate of #139 because my current PR doesn't fix this.

**Comment by timfish** [comment] 2024-07-15 23:44
Oh wow, so this issues is caused by the fact that we are finding a duplicate export named `or`. Duplicate named exports are usually not exported up though tho the root of the module although they are in this case because they come from the same srouce file.

A simpler reproduction:
`a.mjs`
```ts
export const val = 1;
```

`b.mjs`
```ts
export * from './a.mjs';
```

`c.mjs`
```ts
export * from './a.mjs';
export * from './b.mjs';
```
`c.mjs` should have a single export named `val`.

We are not currently checking if duplicate named exports are from the same source file and are in fact, not duplicates.

**Comment by BryceMehring** [comment] 2024-10-21 18:31
Is this planned on getting fixed? Currently right now I'm importing the CJS build of drizzle-orm instead of the ESM version to avoid this issue.

**Comment by jsumners-nr** [comment] 2024-10-21 19:04
You are welcome to submit a PR with a fix.

**Comment by timfish** [comment] 2024-12-13 19:59
Closing in favour of #171 which explains the core issue in the top post.

**Closed by timfish** 2024-12-13 19:59 UTC
