### ISSUE TITLE
import-in-the-middle crashes the directus app

### ISSUE THREAD

**Issue by coignite-user** [nodejs/import-in-the-middle#169] opened 2024-12-12 09:32 UTC
## Expected Behavior
Not to crash

## Actual Behavior
```
file:///workspace/node_modules/node-machine-id/dist/index.js?iitm=true:23
       let $electron-machine-id = _.electron-machine-id
                    ^
 
SyntaxError: Unexpected token '-'
     at ModuleLoader.moduleStrategy (node:internal/modules/esm/translators:168:18)
     at callTranslator (node:internal/modules/esm/loader:279:14)
     at ModuleLoader.moduleProvider (node:internal/modules/esm/loader:285:30)
```
## Steps to Reproduce the Problem
start.js
```
import {config} from 'dotenv';
import {startServer} from '@directus/api/server';
config();
startServer();
```
  1. Setup directus
  2. `npm install newrelic`
  3. Run `npx directus bootstrap && node --experimental-loader newrelic/esm-loader.mjs -r newrelic scripts/start.js`
  4. Watch it crash

## Specifications
* Environment: Docker
* Node: v21.7.3
* OS: 4.4.0 x86_64 GNU/Linux
* Directus: 11.3.2
* newrelic: 12.8.2
* import-in-the-middle: 1.11.3
* node-machine-id: 1.1.12

**Comment by timfish** [comment] 2024-12-12 10:56
I think this is a duplicate of #94

**Closed** 2024-12-13 20:01 UTC
