### ISSUE TITLE
SyntaxError when importing a JSON file using { type: 'json' }

### ISSUE THREAD

**Issue by inaiat** [nodejs/import-in-the-middle#110] opened 2024-06-18 18:20 UTC
## Expected Behavior
The import statement should successfully import the JSON file.

## Actual Behavior
A "SyntaxError" is thrown.

## Steps to Reproduce the Problem

  1. Import json file using with specific syntax ( **with { type: 'json'}**  ):
`import data from './data.json' with { type: 'json' };`
  2. So I updated import-in-the-middle to 1.8.0 (Note that this works fine on version 1.7.3)
  3. After running project I gettting this error:
 `{
      "type": "SyntaxError",
      "message": "Unexpected token (1:818) at SyntaxError: Unexpected token (1:818)",
      "stack":
          SyntaxError: Unexpected token (1:818)
              at pp$4.raise (/Users/inaiat/app/node_modules/.pnpm/acorn@8.12.0/node_modules/acorn/dist/acorn.js:3586:15)
              at pp$9.unexpected (/Users/inaiat/app/node_modules/.pnpm/acorn@8.12.0/node_modules/acorn/dist/acorn.js:772:10)
              at pp$9.semicolon (/Users/inaiat/app/node_modules/.pnpm/acorn@8.12.0/node_modules/acorn/dist/acorn.js:749:68)
              at Parser.parseImport (/Users/inaiat/app/node_modules/.pnpm/acorn-import-attributes@1.9.5_acorn@8.12.0/node_modules/acorn-import-attributes/lib/index.js:242:12)
              at pp$8.parseStatement (/Users/inaiat/app/node_modules/.pnpm/acorn@8.12.0/node_modules/acorn/dist/acorn.js:948:51)
              at pp$8.parseTopLevel (/Users/inaiat/app/node_modules/.pnpm/acorn@8.12.0/node_modules/acorn/dist/acorn.js:829:23)
              at Parser.parse (/Users/inaiat/app/node_modules/.pnpm/acorn@8.12.0/node_modules/acorn/dist/acorn.js:601:17)
              at Function.parse (/Users/inaiat/app/node_modules/.pnpm/acorn@8.12.0/node_modules/acorn/dist/acorn.js:651:37)
              at getEsmExports (/Users/inaiat/app/node_modules/.pnpm/import-in-the-middle@1.8.0/node_modules/import-in-the-middle/lib/get-esm-exports.js:37:23)
              at getExports (/Users/inaiat/app/node_modules/.pnpm/import-in-the-middle@1.8.0/node_modules/import-in-the-middle/lib/get-exports.js:73:12)
      "pos": 818,
      "loc": {
        "line": 1,
        "column": 818
      },
      "raisedAt": 822
    }`

## Specifications

  - Version: 1.8.0
  - Platform: macOS Apple Silicon / Debian
  - Subsystem: nodejs version 22.3.0

**Comment by timfish** [comment] 2024-06-18 18:32
This was fixed by #104

**Comment by inaiat** [comment] 2024-06-18 19:12
@timfish Thanks!

**Comment by timfish** [comment] 2024-06-28 21:40
This is a duplicate of #105 but #104 does help work around the issue

**Closed by timfish** 2024-06-28 21:40 UTC
